from app.forms.service_form import ServiceForm
from app.forms.menu_form import MenuItemForm
from app.forms.page_form import PageForm
from app.forms.home_section_form import HomeSectionForm
from app.forms.login_form import LoginForm
from app.forms.user_form import UserForm
from app.forms.team_member_form import TeamMemberForm
from app.forms.category_form import CategoryForm
from app.forms.product_form import ProductForm
from app.forms.project_form import ProjectForm
from app.forms.post_form import PostForm